### ISSUE TITLE
导出多表头时报合并异常

### ISSUE THREAD

**Issue by CLZSheng** [alibaba/easyexcel#304]
导出多表头时报java.lang.IllegalStateException: Cannot add merged region F3:L3 to sheet because it overlaps with an existing merged region (E3:K3).
无法将合并区域F3:L3添加到工作表，因为它与现有合并区域（E3:K3）重叠。

**Comment by fish7790714** [comment]
上代码

**Comment by gnng** [comment]
如果多层表头，下层表头名相同，可能出现错乱，也可能可能会报上述错误（java.lang.IllegalStateException: Cannot add merged region F3:L3 to sheet because it overlaps with an existing merged region (E3:K3).）。
解决方法：下层表头名不要重复，可以用空格隔开。
![image](https://user-images.githubusercontent.com/30435488/61697022-00512500-ad69-11e9-83b2-0f3a35170f49.png)

**Comment by jaaaar** [comment]
@gnng 不行  还是报错  但是region的位置变了，可以确定的是最后一列已经没有重复值了

**Comment by zhuangjiaju** [comment]
合并算法老版本有BUG，升级到最新版本已经重写了合并的算法。
